import './globals.css'
import {  Rubik } from 'next/font/google'
import Navbar from "@/app/components/Navbar";

const rubik = Rubik({ subsets: ['latin'] })

export const metadata = {
  title: 'iGuion',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
      <html lang="en">
      <head>
        <title>iGuion</title>
      </head>
      <body className={rubik.className}>
      {/*<Navbar />*/}
      {children}
      </body>
      </html>
  )
}
